export enum ToolTypeEnum {
  drag = 'drag',
  marker = 'marker',
  text = 'text',
  polyline = 'polyline',
  polygon = 'polygon',
  circle = 'circle',
  rectangle = 'rectangle',
  ruler = 'ruler',
  measure = 'measure',
  straightArrow = 'straightArrow',
  fineArrow = 'fineArrow',
  assaultDirection = 'assaultDirection',
  squadCombat = 'squadCombat',
  tailedSquadCombat = 'tailedSquadCombat',
  doubleArrow = 'doubleArrow',
  attackArrow = 'attackArrow',
  downfile = 'downfile',
  openfile = 'openfile',
}
