export { setupAntd } from '@/plugins/antd'
export { setupAssets } from '@/plugins/assets'
export { setupTinymce } from '@/plugins/tinymce'
export { setupUpdater } from '@/plugins/updater'
export { setupDirectives } from '@/plugins/directives'
export { setupOther } from '@/plugins/other'
